export class ContactsView {
        id  : number
        transaction_number  : string
        related_to  : string
        related_to_name  : string
        related_to_id  : number
        contact_enabled  : string
        contact_title  : string
        contact_fname  : string
        contact_mname  : string
        contact_lname  : string
        contact_full_name  : string
        contact_address1  : string
        contact_address2  : string
        contact_address3  : string
        contact_city_code  : string 
        contact_zip_code  : string
        contact_state_code  : string 
        contact_country_code  : string
        contact_birthday  : Date
        contact_anniversaray  : Date
        contact_dept_id  : number 
        contact_desig_id  : number
        contact_team_id  :number
        contact_seniority  :string
        contact_profession  : string
        contact_manager  : string 
        contact_extension  : string
        owner_id  : number
        owner_name  : string
        contact_shareable  : string
        created_ip  : string
        created_by  : number
        created_date  : Date
        modified_by  : number
        modified_date  : Date
        modified_ip  : string
        last_activity_date  : Date
        contact_timezone_id  : number
        contact_timezone_timespan  : number
        contact_type_id  : string
        contact_login_id  : string
        contact_password  : string
        contact_current_theme  : string
        contact_show_menubar  : string
        contact_show_toolbar  : string
        contact_show_alertbar  : string
        contact_show_popup  : string
        Useable  : string
        contact_phone  : string
        contact_emailid  : string
        custom_tab_name  : string
        custom_tab_url  : string
        contact_role_id  : number
        contact_signature  : string
        contact_cti_url  : string
        cti_url  : string
        cust_reportingtocolumn  : number
        contact_chat_status  : string
        contact_zone  : string
        api_key  : string
        custportal_contactId  : string
        crm_contact_code  : string
}
