export class LocationView {
    id : number
    transaction_number : string
    cust_name  : string
    cust_name2 : string
    cust_short_name : string
    cust_enabled  : string
    cust_type  : string
    cust_zone  : string
    cust_address1  : string
    cust_address2  : string
    cust_address3  : string
    cust_city_code  : string
    cust_state_code  : string
    cust_zip_code  : string
    cust_tin_no  : string
    cust_pan_no  : string
    cust_category  : string
    cust_rating  : string
    cust_extension  : string
    cust_website_address  : string
    cust_country_code  : string
    cust_tan_no  : string
    cust_service_tax_no  : string
    cust_tax_scheme_id  : number
    owner_id : number
    owner_name : string
    created_by : number
    created_ip  : string
    created_date  : Date
    modified_by  : number
    modified_date  : Date
    modified_ip  : string
    last_activity_date  : Date
    cust_case_notifcation  : string
    cust_notify_caller  : string
    cust_notify_contact  : string
    cust_case_notification_to  : string
    useable  : string
    custom_tab_name  : string
    custom_tab_url  : string
    cust_phone  : string
    cust_emailid  : string
    cust_domain  : string
    cust_ValidityStatus  : string
    cust_Expiry_date  : Date
    cust_saleslocation  : string
    cust_saleslocation_id  : number
    cust_salesPerson  : string
    cust_salesPerson_id  : number
    cust_serviceLocation  : string
    cust_serviceLocation_id  : number
    cust_ServiceBy  : string
    cust_ServiceBy_id  : number
}
