export class TicketView {
    id : number
    transaction_number : string
    owner_id : number 
    case_source : string
    case_source_value : string
    case_customer_id : number 
    case_customer_name : string
    case_caller_id : number 
    case_caller_name : string
    case_caller_phone : string
    case_caller_email : string
    case_contact_id : number 
    case_contact_name : string
    case_contact_phone : string
    case_contact_email : string
    case_service_type_name : string
    case_severity_desc : string
    case_subject : string
    case_description : string
    case_type_id : string
    case_type_name : string
    case_status_id : string
    case_status_name : string
    case_status_reason_id : string
    case_status_reason_desc : string
    case_inventory_id : number 
    case_serial_number : string
    case_category_id : string
    case_category_name : string
    case_subcategory_id : string
    case_subcategory_name : string
    case_reference_data : string
    open_time : Date
    target_end_time : Date
    end_time : Date
    end_remarks : string
    created_ip : string
    created_by : number 
    created_date : Date
    modified_by : number
    modified_date : Date
    modified_ip : string
    last_activity_date : Date
    case_severity_id : number 
    case_service_type_id : number
    Useable : string
    custom_tab_name : string
    custom_tab_url : string
    assign_level : number 
    case_callback_number : string
    case_reassigned_time : Date
    first_open_time : Date
    case_notification_modifyby : string
    case_notification_closer : string
    next_status_time : Date
    Location_name : string
    Location_id : number 
    Team_name : string
    Team_id : number 
    close_time : Date
    assign_to_id : number
    assign_to_Location_name : string
    assign_to_Location_id : number 
    assign_to_Team_name : string
    assign_to_Team_id : number 
    case_account_validity : string
    response_time :Date
    work_close_time : Date
    working_time : number
    case_repeat_call : string
    case_close_type : string
}
