export class AssetsView {
id : number
inv_status : string
inv_product_id : number
inv_product_name : string
inv_serial_no :  string
owner_id : number
related_to_id : number
related_to_name : string
inv_warranty_start_date : Date
inv_warranty_end_date : Date
inv_contract_start_date : Date
inv_installation_date : Date
inv_sale_date : Date
created_ip : string
created_by : number
created_date : Date
modified_by : number
modified_date : Date 
modified_ip : string
last_activity_date : Date
Useable : string
custom_tab_name : string
custom_tab_url : string
owner_name : string
related_to : string
transaction_number : string
udf_machine_expiry_date : Date
asset_category_id : number
asset_category : string
asset_sub_category_id : string
asset_sub_category : string
asset_product_type : string
asset_vender_name : string
asset_vender_id : string
asset_software_type_id : number
asset_software_type : string
asset_software_category_id : number
asset_software_category : string
asset_asset_make : string
asset_model :  string
asset_OEM_serial_number : string
asset_issue_sparese : string
asset_porpose_process : string
asset_owned_lease : string
asset_purchase_date : string
asset_amount : string
asset_currency : string
asset_product_type_id : string
asset_desc : string
}
